// Package domain holds the media bounded context's business types: an
// uploaded MediaAsset and the typed errors it raises. It imports nothing from
// the app, adapters, or transport layers.
package domain

import (
	"path"
	"strings"
	"time"

	"github.com/nikolaymatrosov/nvelope/internal/platform/apperr"
)

// allowedContentTypes is the allowlist of MIME types a tenant may upload. It
// is deliberately small: the public capability URLs serve these bytes to
// browsers and email clients, so the platform restricts what content can ride
// that surface (FR-025).
var allowedContentTypes = map[string]bool{
	"image/png":       true,
	"image/jpeg":      true,
	"image/gif":       true,
	"image/webp":      true,
	"image/svg+xml":   true,
	"application/pdf": true,
}

// AllowedContentTypes returns the set of MIME types accepted on upload, in a
// stable order, for the admin UI / error messages.
func AllowedContentTypes() []string {
	out := make([]string, 0, len(allowedContentTypes))
	for t := range allowedContentTypes {
		out = append(out, t)
	}
	return out
}

// MediaAsset is one file a tenant has uploaded to the media library. Metadata
// (this row) is tenant-scoped under RLS; the bytes live in object storage at
// a tenant-prefixed, unguessable key.
type MediaAsset struct {
	id          string
	tenantID    string
	filename    string
	contentType string
	sizeBytes   int64
	storageKey  string
	publicURL   string
	uploadedBy  string
	createdAt   time.Time
}

// sanitiseFilename strips any directory component a client may have sent and
// rejects an empty result. It does not enforce a character allowlist — the
// filename is only ever written into the object key (which is URL-encoded by
// the SDK) and surfaced as a display string.
func sanitiseFilename(filename string) (string, error) {
	cleaned := path.Base(strings.TrimSpace(filename))
	if cleaned == "" || cleaned == "." || cleaned == "/" {
		return "", ErrEmptyFilename
	}
	return cleaned, nil
}

// NewMediaAsset builds a media asset, rejecting any invariant violation. The
// id is generated by the caller (the use case) so it can be embedded in the
// storage key before the bytes are written. maxBytes is the per-file cap set
// by configuration.
func NewMediaAsset(id, tenantID, filename, contentType string, sizeBytes, maxBytes int64,
	storageKey, publicURL, uploadedBy string) (*MediaAsset, error) {

	if id == "" {
		return nil, apperr.NewIncorrectInput("validation_failed", "a media asset id is required")
	}
	if tenantID == "" {
		return nil, apperr.NewIncorrectInput("validation_failed", "a tenant is required")
	}
	cleanName, err := sanitiseFilename(filename)
	if err != nil {
		return nil, err
	}
	if !allowedContentTypes[strings.ToLower(strings.TrimSpace(contentType))] {
		return nil, ErrUnsupportedMediaType
	}
	if sizeBytes <= 0 {
		return nil, ErrEmptyUpload
	}
	if sizeBytes > maxBytes {
		return nil, ErrMediaTooLarge
	}
	if storageKey == "" || publicURL == "" {
		return nil, apperr.NewIncorrectInput("validation_failed",
			"a storage key and public url are required")
	}
	return &MediaAsset{
		id:          id,
		tenantID:    tenantID,
		filename:    cleanName,
		contentType: strings.ToLower(strings.TrimSpace(contentType)),
		sizeBytes:   sizeBytes,
		storageKey:  storageKey,
		publicURL:   publicURL,
		uploadedBy:  uploadedBy,
	}, nil
}

// HydrateMediaAsset reconstructs a media asset from a persisted row.
// Persistence only — it performs no validation.
func HydrateMediaAsset(id, tenantID, filename, contentType string, sizeBytes int64,
	storageKey, publicURL, uploadedBy string, createdAt time.Time) *MediaAsset {
	return &MediaAsset{
		id:          id,
		tenantID:    tenantID,
		filename:    filename,
		contentType: contentType,
		sizeBytes:   sizeBytes,
		storageKey:  storageKey,
		publicURL:   publicURL,
		uploadedBy:  uploadedBy,
		createdAt:   createdAt,
	}
}

// ID returns the asset's database-assigned id (also the unguessable key
// segment).
func (a *MediaAsset) ID() string { return a.id }

// TenantID returns the owning tenant's id.
func (a *MediaAsset) TenantID() string { return a.tenantID }

// Filename returns the sanitised original filename.
func (a *MediaAsset) Filename() string { return a.filename }

// ContentType returns the MIME type.
func (a *MediaAsset) ContentType() string { return a.contentType }

// SizeBytes returns the file size in bytes.
func (a *MediaAsset) SizeBytes() int64 { return a.sizeBytes }

// StorageKey returns the object-storage key.
func (a *MediaAsset) StorageKey() string { return a.storageKey }

// PublicURL returns the stable, publicly fetchable URL.
func (a *MediaAsset) PublicURL() string { return a.publicURL }

// UploadedBy returns the user id that uploaded the asset, or "".
func (a *MediaAsset) UploadedBy() string { return a.uploadedBy }

// CreatedAt returns when the asset was uploaded.
func (a *MediaAsset) CreatedAt() time.Time { return a.createdAt }
