/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsNewRouteImport } from './routes/tenants/new'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as TSlugRouteRouteImport } from './routes/t/$slug/route'
import { Route as TSlugIndexRouteImport } from './routes/t/$slug/index'
import { Route as TSlugTransactionalIndexRouteImport } from './routes/t/$slug/transactional/index'
import { Route as TSlugTemplatesIndexRouteImport } from './routes/t/$slug/templates/index'
import { Route as TSlugSubscribersIndexRouteImport } from './routes/t/$slug/subscribers/index'
import { Route as TSlugSettingsIndexRouteImport } from './routes/t/$slug/settings/index'
import { Route as TSlugSendingDomainsIndexRouteImport } from './routes/t/$slug/sending-domains/index'
import { Route as TSlugSecurityIndexRouteImport } from './routes/t/$slug/security/index'
import { Route as TSlugListsIndexRouteImport } from './routes/t/$slug/lists/index'
import { Route as TSlugImportExportIndexRouteImport } from './routes/t/$slug/import-export/index'
import { Route as TSlugCampaignsIndexRouteImport } from './routes/t/$slug/campaigns/index'
import { Route as TSlugAuditIndexRouteImport } from './routes/t/$slug/audit/index'
import { Route as TSlugAccessIndexRouteImport } from './routes/t/$slug/access/index'
import { Route as TSlugTemplatesIdRouteImport } from './routes/t/$slug/templates/$id'
import { Route as TSlugSubscribersIdRouteImport } from './routes/t/$slug/subscribers/$id'
import { Route as TSlugSendingDomainsIdRouteImport } from './routes/t/$slug/sending-domains/$id'
import { Route as TSlugListsIdRouteImport } from './routes/t/$slug/lists/$id'
import { Route as TSlugCampaignsIdRouteImport } from './routes/t/$slug/campaigns/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsNewRoute = TenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRouteRoute = TSlugRouteRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugTransactionalIndexRoute = TSlugTransactionalIndexRouteImport.update({
  id: '/transactional/',
  path: '/transactional/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugTemplatesIndexRoute = TSlugTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugSubscribersIndexRoute = TSlugSubscribersIndexRouteImport.update({
  id: '/subscribers/',
  path: '/subscribers/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugSettingsIndexRoute = TSlugSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugSendingDomainsIndexRoute =
  TSlugSendingDomainsIndexRouteImport.update({
    id: '/sending-domains/',
    path: '/sending-domains/',
    getParentRoute: () => TSlugRouteRoute,
  } as any)
const TSlugSecurityIndexRoute = TSlugSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugListsIndexRoute = TSlugListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugImportExportIndexRoute = TSlugImportExportIndexRouteImport.update({
  id: '/import-export/',
  path: '/import-export/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugCampaignsIndexRoute = TSlugCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugAuditIndexRoute = TSlugAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugAccessIndexRoute = TSlugAccessIndexRouteImport.update({
  id: '/access/',
  path: '/access/',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugTemplatesIdRoute = TSlugTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugSubscribersIdRoute = TSlugSubscribersIdRouteImport.update({
  id: '/subscribers/$id',
  path: '/subscribers/$id',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugSendingDomainsIdRoute = TSlugSendingDomainsIdRouteImport.update({
  id: '/sending-domains/$id',
  path: '/sending-domains/$id',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugListsIdRoute = TSlugListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => TSlugRouteRoute,
} as any)
const TSlugCampaignsIdRoute = TSlugCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => TSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/t/$slug': typeof TSlugRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/tenants/new': typeof TenantsNewRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/campaigns/$id': typeof TSlugCampaignsIdRoute
  '/t/$slug/lists/$id': typeof TSlugListsIdRoute
  '/t/$slug/sending-domains/$id': typeof TSlugSendingDomainsIdRoute
  '/t/$slug/subscribers/$id': typeof TSlugSubscribersIdRoute
  '/t/$slug/templates/$id': typeof TSlugTemplatesIdRoute
  '/t/$slug/access/': typeof TSlugAccessIndexRoute
  '/t/$slug/audit/': typeof TSlugAuditIndexRoute
  '/t/$slug/campaigns/': typeof TSlugCampaignsIndexRoute
  '/t/$slug/import-export/': typeof TSlugImportExportIndexRoute
  '/t/$slug/lists/': typeof TSlugListsIndexRoute
  '/t/$slug/security/': typeof TSlugSecurityIndexRoute
  '/t/$slug/sending-domains/': typeof TSlugSendingDomainsIndexRoute
  '/t/$slug/settings/': typeof TSlugSettingsIndexRoute
  '/t/$slug/subscribers/': typeof TSlugSubscribersIndexRoute
  '/t/$slug/templates/': typeof TSlugTemplatesIndexRoute
  '/t/$slug/transactional/': typeof TSlugTransactionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/tenants/new': typeof TenantsNewRoute
  '/t/$slug': typeof TSlugIndexRoute
  '/t/$slug/campaigns/$id': typeof TSlugCampaignsIdRoute
  '/t/$slug/lists/$id': typeof TSlugListsIdRoute
  '/t/$slug/sending-domains/$id': typeof TSlugSendingDomainsIdRoute
  '/t/$slug/subscribers/$id': typeof TSlugSubscribersIdRoute
  '/t/$slug/templates/$id': typeof TSlugTemplatesIdRoute
  '/t/$slug/access': typeof TSlugAccessIndexRoute
  '/t/$slug/audit': typeof TSlugAuditIndexRoute
  '/t/$slug/campaigns': typeof TSlugCampaignsIndexRoute
  '/t/$slug/import-export': typeof TSlugImportExportIndexRoute
  '/t/$slug/lists': typeof TSlugListsIndexRoute
  '/t/$slug/security': typeof TSlugSecurityIndexRoute
  '/t/$slug/sending-domains': typeof TSlugSendingDomainsIndexRoute
  '/t/$slug/settings': typeof TSlugSettingsIndexRoute
  '/t/$slug/subscribers': typeof TSlugSubscribersIndexRoute
  '/t/$slug/templates': typeof TSlugTemplatesIndexRoute
  '/t/$slug/transactional': typeof TSlugTransactionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/t/$slug': typeof TSlugRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/tenants/new': typeof TenantsNewRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/campaigns/$id': typeof TSlugCampaignsIdRoute
  '/t/$slug/lists/$id': typeof TSlugListsIdRoute
  '/t/$slug/sending-domains/$id': typeof TSlugSendingDomainsIdRoute
  '/t/$slug/subscribers/$id': typeof TSlugSubscribersIdRoute
  '/t/$slug/templates/$id': typeof TSlugTemplatesIdRoute
  '/t/$slug/access/': typeof TSlugAccessIndexRoute
  '/t/$slug/audit/': typeof TSlugAuditIndexRoute
  '/t/$slug/campaigns/': typeof TSlugCampaignsIndexRoute
  '/t/$slug/import-export/': typeof TSlugImportExportIndexRoute
  '/t/$slug/lists/': typeof TSlugListsIndexRoute
  '/t/$slug/security/': typeof TSlugSecurityIndexRoute
  '/t/$slug/sending-domains/': typeof TSlugSendingDomainsIndexRoute
  '/t/$slug/settings/': typeof TSlugSettingsIndexRoute
  '/t/$slug/subscribers/': typeof TSlugSubscribersIndexRoute
  '/t/$slug/templates/': typeof TSlugTemplatesIndexRoute
  '/t/$slug/transactional/': typeof TSlugTransactionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/t/$slug'
    | '/invite/$token'
    | '/tenants/new'
    | '/t/$slug/'
    | '/t/$slug/campaigns/$id'
    | '/t/$slug/lists/$id'
    | '/t/$slug/sending-domains/$id'
    | '/t/$slug/subscribers/$id'
    | '/t/$slug/templates/$id'
    | '/t/$slug/access/'
    | '/t/$slug/audit/'
    | '/t/$slug/campaigns/'
    | '/t/$slug/import-export/'
    | '/t/$slug/lists/'
    | '/t/$slug/security/'
    | '/t/$slug/sending-domains/'
    | '/t/$slug/settings/'
    | '/t/$slug/subscribers/'
    | '/t/$slug/templates/'
    | '/t/$slug/transactional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/invite/$token'
    | '/tenants/new'
    | '/t/$slug'
    | '/t/$slug/campaigns/$id'
    | '/t/$slug/lists/$id'
    | '/t/$slug/sending-domains/$id'
    | '/t/$slug/subscribers/$id'
    | '/t/$slug/templates/$id'
    | '/t/$slug/access'
    | '/t/$slug/audit'
    | '/t/$slug/campaigns'
    | '/t/$slug/import-export'
    | '/t/$slug/lists'
    | '/t/$slug/security'
    | '/t/$slug/sending-domains'
    | '/t/$slug/settings'
    | '/t/$slug/subscribers'
    | '/t/$slug/templates'
    | '/t/$slug/transactional'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/t/$slug'
    | '/invite/$token'
    | '/tenants/new'
    | '/t/$slug/'
    | '/t/$slug/campaigns/$id'
    | '/t/$slug/lists/$id'
    | '/t/$slug/sending-domains/$id'
    | '/t/$slug/subscribers/$id'
    | '/t/$slug/templates/$id'
    | '/t/$slug/access/'
    | '/t/$slug/audit/'
    | '/t/$slug/campaigns/'
    | '/t/$slug/import-export/'
    | '/t/$slug/lists/'
    | '/t/$slug/security/'
    | '/t/$slug/sending-domains/'
    | '/t/$slug/settings/'
    | '/t/$slug/subscribers/'
    | '/t/$slug/templates/'
    | '/t/$slug/transactional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TSlugRouteRoute: typeof TSlugRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  TenantsNewRoute: typeof TenantsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/new': {
      id: '/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof TenantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/transactional/': {
      id: '/t/$slug/transactional/'
      path: '/transactional'
      fullPath: '/t/$slug/transactional/'
      preLoaderRoute: typeof TSlugTransactionalIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/templates/': {
      id: '/t/$slug/templates/'
      path: '/templates'
      fullPath: '/t/$slug/templates/'
      preLoaderRoute: typeof TSlugTemplatesIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/subscribers/': {
      id: '/t/$slug/subscribers/'
      path: '/subscribers'
      fullPath: '/t/$slug/subscribers/'
      preLoaderRoute: typeof TSlugSubscribersIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/settings/': {
      id: '/t/$slug/settings/'
      path: '/settings'
      fullPath: '/t/$slug/settings/'
      preLoaderRoute: typeof TSlugSettingsIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/sending-domains/': {
      id: '/t/$slug/sending-domains/'
      path: '/sending-domains'
      fullPath: '/t/$slug/sending-domains/'
      preLoaderRoute: typeof TSlugSendingDomainsIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/security/': {
      id: '/t/$slug/security/'
      path: '/security'
      fullPath: '/t/$slug/security/'
      preLoaderRoute: typeof TSlugSecurityIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/lists/': {
      id: '/t/$slug/lists/'
      path: '/lists'
      fullPath: '/t/$slug/lists/'
      preLoaderRoute: typeof TSlugListsIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/import-export/': {
      id: '/t/$slug/import-export/'
      path: '/import-export'
      fullPath: '/t/$slug/import-export/'
      preLoaderRoute: typeof TSlugImportExportIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/campaigns/': {
      id: '/t/$slug/campaigns/'
      path: '/campaigns'
      fullPath: '/t/$slug/campaigns/'
      preLoaderRoute: typeof TSlugCampaignsIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/audit/': {
      id: '/t/$slug/audit/'
      path: '/audit'
      fullPath: '/t/$slug/audit/'
      preLoaderRoute: typeof TSlugAuditIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/access/': {
      id: '/t/$slug/access/'
      path: '/access'
      fullPath: '/t/$slug/access/'
      preLoaderRoute: typeof TSlugAccessIndexRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/templates/$id': {
      id: '/t/$slug/templates/$id'
      path: '/templates/$id'
      fullPath: '/t/$slug/templates/$id'
      preLoaderRoute: typeof TSlugTemplatesIdRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/subscribers/$id': {
      id: '/t/$slug/subscribers/$id'
      path: '/subscribers/$id'
      fullPath: '/t/$slug/subscribers/$id'
      preLoaderRoute: typeof TSlugSubscribersIdRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/sending-domains/$id': {
      id: '/t/$slug/sending-domains/$id'
      path: '/sending-domains/$id'
      fullPath: '/t/$slug/sending-domains/$id'
      preLoaderRoute: typeof TSlugSendingDomainsIdRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/lists/$id': {
      id: '/t/$slug/lists/$id'
      path: '/lists/$id'
      fullPath: '/t/$slug/lists/$id'
      preLoaderRoute: typeof TSlugListsIdRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
    '/t/$slug/campaigns/$id': {
      id: '/t/$slug/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/t/$slug/campaigns/$id'
      preLoaderRoute: typeof TSlugCampaignsIdRouteImport
      parentRoute: typeof TSlugRouteRoute
    }
  }
}

interface TSlugRouteRouteChildren {
  TSlugIndexRoute: typeof TSlugIndexRoute
  TSlugCampaignsIdRoute: typeof TSlugCampaignsIdRoute
  TSlugListsIdRoute: typeof TSlugListsIdRoute
  TSlugSendingDomainsIdRoute: typeof TSlugSendingDomainsIdRoute
  TSlugSubscribersIdRoute: typeof TSlugSubscribersIdRoute
  TSlugTemplatesIdRoute: typeof TSlugTemplatesIdRoute
  TSlugAccessIndexRoute: typeof TSlugAccessIndexRoute
  TSlugAuditIndexRoute: typeof TSlugAuditIndexRoute
  TSlugCampaignsIndexRoute: typeof TSlugCampaignsIndexRoute
  TSlugImportExportIndexRoute: typeof TSlugImportExportIndexRoute
  TSlugListsIndexRoute: typeof TSlugListsIndexRoute
  TSlugSecurityIndexRoute: typeof TSlugSecurityIndexRoute
  TSlugSendingDomainsIndexRoute: typeof TSlugSendingDomainsIndexRoute
  TSlugSettingsIndexRoute: typeof TSlugSettingsIndexRoute
  TSlugSubscribersIndexRoute: typeof TSlugSubscribersIndexRoute
  TSlugTemplatesIndexRoute: typeof TSlugTemplatesIndexRoute
  TSlugTransactionalIndexRoute: typeof TSlugTransactionalIndexRoute
}

const TSlugRouteRouteChildren: TSlugRouteRouteChildren = {
  TSlugIndexRoute: TSlugIndexRoute,
  TSlugCampaignsIdRoute: TSlugCampaignsIdRoute,
  TSlugListsIdRoute: TSlugListsIdRoute,
  TSlugSendingDomainsIdRoute: TSlugSendingDomainsIdRoute,
  TSlugSubscribersIdRoute: TSlugSubscribersIdRoute,
  TSlugTemplatesIdRoute: TSlugTemplatesIdRoute,
  TSlugAccessIndexRoute: TSlugAccessIndexRoute,
  TSlugAuditIndexRoute: TSlugAuditIndexRoute,
  TSlugCampaignsIndexRoute: TSlugCampaignsIndexRoute,
  TSlugImportExportIndexRoute: TSlugImportExportIndexRoute,
  TSlugListsIndexRoute: TSlugListsIndexRoute,
  TSlugSecurityIndexRoute: TSlugSecurityIndexRoute,
  TSlugSendingDomainsIndexRoute: TSlugSendingDomainsIndexRoute,
  TSlugSettingsIndexRoute: TSlugSettingsIndexRoute,
  TSlugSubscribersIndexRoute: TSlugSubscribersIndexRoute,
  TSlugTemplatesIndexRoute: TSlugTemplatesIndexRoute,
  TSlugTransactionalIndexRoute: TSlugTransactionalIndexRoute,
}

const TSlugRouteRouteWithChildren = TSlugRouteRoute._addFileChildren(
  TSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TSlugRouteRoute: TSlugRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  TenantsNewRoute: TenantsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
