// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  account: {
    back: "Back"
    description: "Manage your personal preferences. These apply to your account everywhere you sign in."
    language: {
      cardDescription: "Choose the language for the nvelope interface."
      hint: "Applies across all your workspaces and devices."
      label: "Interface language"
      title: "Language"
    }
    title: "Account settings"
  }
  auth: {
    invite: {
      errorTitle: "Could not accept the invitation"
      goToSignIn: "Go to sign in"
      haveAccountHint: "Already have an account? Log in first, then open this link again."
      invalidDescription: "This invitation has expired, been revoked, or already been used."
      invalidTitle: "Invitation not valid"
      joinDescription: "You were invited as {{email}}. Create your account to join."
      joinTitle: "Join {{workspace}}"
      name: "Your name"
      nameRequired: "Enter your name."
      password: "Choose a password"
      passwordHint: "At least 8 characters."
      passwordTooShort: "Use at least 8 characters."
      submit: "Accept invitation"
      submitting: "Joining…"
    }
    login: {
      description: "Welcome back. Sign in to your workspaces."
      email: "Email"
      errorTitle: "Could not sign in"
      invalidCredentials: "That email and password do not match."
      needAccount: "Need an account?"
      password: "Password"
      signUpLink: "Sign up"
      submit: "Log in"
      submitting: "Signing in…"
      title: "Log in to nvelope"
    }
    signup: {
      description: "Sign up, then create your first workspace."
      email: "Email"
      emailTaken: "An account with this email already exists."
      errorTitle: "Sign-up failed"
      haveAccount: "Already have an account?"
      logInLink: "Log in"
      name: "Name"
      nameRequired: "Enter your name."
      password: "Password"
      passwordHint: "At least 8 characters."
      passwordTooShort: "Use at least 8 characters."
      submit: "Sign up"
      submitting: "Creating…"
      title: "Create your nvelope account"
    }
  }
  common: {
    account: {
      menu: "Account menu"
      settings: "Account settings"
      signOut: "Sign out"
      switchWorkspace: "Switch workspace"
    }
    actions: {
      cancel: "Cancel"
      save: "Save"
      saving: "Saving…"
    }
    nav: {
      access: "People & Access"
      audit: "Audit"
      billing: "Billing"
      branding: "Branding"
      campaigns: "Campaigns"
      dashboard: "Dashboard"
      group: "Workspace"
      importExport: "Import / Export"
      lists: "Lists"
      media: "Media"
      publicPages: "Public pages"
      sendingDomains: "Sending Domains"
      settings: "Settings"
      subscribers: "Subscribers"
      suppressions: "Suppression list"
      templates: "Templates"
      transactional: "Transactional Sending"
    }
    state: {
      error: "Something went wrong."
      loading: "Loading…"
    }
  }
}
