// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "access": {
    "index": {
      "description": "Manage members, invitations, and roles.",
      "title": "People & Access"
    },
    "invitations": {
      "confirmRevokeDescription": "The invitation link will stop working and cannot be reused.",
      "confirmRevokeLabel": "Revoke invitation",
      "confirmRevokeTitle": "Revoke this invitation?",
      "copyLink": "Copy link",
      "emailLabel": "Email address",
      "emptyMessage": "Invitations you send will appear here until accepted.",
      "emptyTitle": "No pending invitations",
      "expires": "Expires {{date}}",
      "inviteRevoked": "Invitation revoked.",
      "inviteSent": "Invitation sent.",
      "inviteTitle": "Invite a teammate",
      "linkCopied": "Link copied.",
      "linkTitle": "Invitation link",
      "revoke": "Revoke",
      "sendInvite": "Send invite"
    },
    "listRoles": {
      "description": "Grant or remove a role scoped to a single list.",
      "grantRole": "Grant role",
      "grantSuccess": "Per-list role granted.",
      "listLabel": "List",
      "listPlaceholder": "Choose a list…",
      "removeRole": "Remove role on list",
      "removeSuccess": "Per-list role removed.",
      "roleLabel": "Role",
      "rolePlaceholder": "Choose a role…",
      "title": "List access for {{name}}"
    },
    "members": {
      "listAccess": "List access",
      "loadErrorTitle": "Could not load members",
      "loading": "Loading members…",
      "roleUpdated": "Role updated.",
      "viewOnlyMessage": "You can see members but need the “roles:manage” permission to change role assignments.",
      "viewOnlyTitle": "View only"
    },
    "roleDialog": {
      "createRole": "Create role",
      "createSuccess": "Role created.",
      "description": "Name the role and choose the permissions it grants.",
      "editTitle": "Edit role",
      "nameLabel": "Role name",
      "nameRequired": "Enter a role name.",
      "newTitle": "New role",
      "permissionsLabel": "Permissions",
      "saveRole": "Save role",
      "saving": "Saving…",
      "updateSuccess": "Role updated."
    },
    "roles": {
      "confirmDeleteDescription": "Members assigned this role will lose its permissions.",
      "confirmDeleteLabel": "Delete role",
      "confirmDeleteTitle": "Delete the “{{name}}” role?",
      "deleteRole": "Delete role",
      "deleteSuccess": "Role deleted.",
      "edit": "Edit",
      "emptyMessage": "Create a role to grant scoped permissions.",
      "emptyTitle": "No roles yet",
      "newRole": "New role",
      "permissionCount_few": "{{count}} permissions",
      "permissionCount_many": "{{count}} permissions",
      "permissionCount_one": "{{count}} permission",
      "permissionCount_other": "{{count}} permissions",
      "unavailableMessage": "You need the “roles:manage” permission to create or change roles.",
      "unavailableTitle": "Role management unavailable"
    },
    "tabs": {
      "invitations": "Invitations",
      "members": "Members",
      "roles": "Roles"
    }
  },
  "account": {
    "back": "Back",
    "description": "Manage your personal preferences. These apply to your account everywhere you sign in.",
    "language": {
      "cardDescription": "Choose the language for the nvelope interface.",
      "hint": "Applies across all your workspaces and devices.",
      "label": "Interface language",
      "title": "Language"
    },
    "title": "Account settings"
  },
  "analytics": {
    "campaign": {
      "awaiting": {
        "description": "Delivery feedback has not been processed for this campaign yet. Counts and rates will appear here once the first refresh runs.",
        "title": "Awaiting data"
      },
      "backToCampaign": "Back to campaign",
      "description": "How this campaign performed across delivery, opens, and clicks.",
      "metrics": {
        "bounced": "Bounced",
        "clicked": "Clicked",
        "complained": "Complained",
        "delivered": "Delivered",
        "opened": "Opened",
        "sent": "Sent"
      },
      "notFound": {
        "description": "This campaign does not exist in this workspace.",
        "title": "Campaign not found"
      },
      "refreshedAt": "Figures last refreshed {{timestamp}}.",
      "title": "Campaign analytics"
    }
  },
  "audit": {
    "columns": {
      "action": "Action",
      "actor": "Actor",
      "target": "Target",
      "when": "When"
    },
    "index": {
      "description": "Recent activity in this workspace.",
      "emptyMessage": "Workspace actions will appear here.",
      "emptyTitle": "No activity yet",
      "title": "Audit trail"
    }
  },
  "auth": {
    "invite": {
      "errorTitle": "Could not accept the invitation",
      "goToSignIn": "Go to sign in",
      "haveAccountHint": "Already have an account? Log in first, then open this link again.",
      "invalidDescription": "This invitation has expired, been revoked, or already been used.",
      "invalidTitle": "Invitation not valid",
      "joinDescription": "You were invited as {{email}}. Create your account to join.",
      "joinTitle": "Join {{workspace}}",
      "name": "Your name",
      "nameRequired": "Enter your name.",
      "password": "Choose a password",
      "passwordHint": "At least 8 characters.",
      "passwordTooShort": "Use at least 8 characters.",
      "submit": "Accept invitation",
      "submitting": "Joining…"
    },
    "login": {
      "description": "Welcome back. Sign in to your workspaces.",
      "email": "Email",
      "emailNotVerified": "Verify your email address before signing in. Check your inbox for the verification link.",
      "errorTitle": "Could not sign in",
      "invalidCredentials": "That email and password do not match.",
      "needAccount": "Need an account?",
      "password": "Password",
      "resendButton": "Resend verification email",
      "resendSending": "Sending…",
      "resendSent": "If that address has an unverified account, a new verification link is on its way.",
      "signUpLink": "Sign up",
      "submit": "Log in",
      "submitting": "Signing in…",
      "title": "Log in to nvelope"
    },
    "signup": {
      "backToLogin": "Back to log in",
      "checkInboxDescription": "We sent a verification link to {{email}}.",
      "checkInboxHint": "Open the link in that email to activate your account, then sign in.",
      "checkInboxTitle": "Check your inbox",
      "description": "Sign up, then create your first workspace.",
      "email": "Email",
      "emailDomainNotAllowed": "Registration is not open to this email domain.",
      "emailTaken": "An account with this email already exists.",
      "errorTitle": "Sign-up failed",
      "haveAccount": "Already have an account?",
      "logInLink": "Log in",
      "name": "Name",
      "nameRequired": "Enter your name.",
      "password": "Password",
      "passwordHint": "At least 8 characters.",
      "passwordTooShort": "Use at least 8 characters.",
      "submit": "Sign up",
      "submitting": "Creating…",
      "title": "Create your nvelope account"
    },
    "verifyEmail": {
      "alreadyVerifiedDescription": "This account has already been verified. You can sign in.",
      "alreadyVerifiedTitle": "Already verified",
      "goToLogin": "Go to log in",
      "invalidDescription": "This verification link is invalid or has expired.",
      "invalidTitle": "Link invalid or expired",
      "missingToken": "This verification link is missing its token.",
      "resendButton": "Send a new link",
      "resendEmailLabel": "Email",
      "resendPrompt": "Need a new link?",
      "resendSending": "Sending…",
      "resendSent": "If that address has an unverified account, a new verification link is on its way.",
      "title": "Email verification",
      "verifiedDescription": "Your email address is confirmed. You can now sign in.",
      "verifiedTitle": "Email verified",
      "verifying": "Verifying your email address…"
    }
  },
  "billing": {
    "invoices": {
      "columns": {
        "billingPeriod": "Billing period",
        "status": "Status",
        "total": "Total"
      },
      "description": "Billing history and payment attempts for this workspace.",
      "detail": {
        "attempt": "Attempt {{number}} — {{status}}",
        "attemptStatus": {
          "failed": "Failed",
          "succeeded": "Succeeded"
        },
        "description": "Line items and payment attempts for this invoice.",
        "lineItemColumns": {
          "amount": "Amount",
          "description": "Description",
          "quantity": "Qty"
        },
        "lineItems": "Line items",
        "noAttempts": "No payment attempts have been made yet.",
        "notFound": "This invoice could not be found.",
        "paymentAttempts": "Payment attempts",
        "title": "Invoice",
        "total": "Total"
      },
      "empty": {
        "description": "Invoices appear here once a billing period has been charged.",
        "title": "No invoices yet"
      },
      "loadError": {
        "title": "Could not load invoices"
      },
      "pagination": {
        "next": "Next",
        "previous": "Previous",
        "range": "{{from}}–{{to}} of {{total}}"
      },
      "status": {
        "open": "Unpaid",
        "paid": "Paid",
        "void": "Void"
      },
      "title": "Invoices"
    },
    "overview": {
      "currentPlan": {
        "fields": {
          "billingPeriod": "Billing period",
          "plan": "Plan",
          "renewal": "Renewal",
          "usageThisPeriod": "Usage this period"
        },
        "overageDescriptionBilled": "Sends over the allowance are billed as overage.",
        "overageDescriptionBlocked": "Sends over the allowance are blocked.",
        "renewalCancels": "Cancels at the end of the current period",
        "title": "Current plan",
        "usageValue": "{{used}} of {{included}} sends"
      },
      "description": "Your plan, subscription status, and account balance.",
      "loadError": {
        "retry": "Try again",
        "title": "Could not load billing"
      },
      "noSubscription": {
        "browsePlans": "Browse plans",
        "description": "This workspace is not subscribed to a plan. Choose a plan to start sending.",
        "title": "No active subscription"
      },
      "settle": {
        "alreadySettled": "That invoice has already been settled.",
        "charge": "Settle balance now",
        "charging": "Charging…",
        "declined": "The payment was declined again. The account remains suspended — please try once more or use a different payment method.",
        "description": "Settle the unpaid invoice to bring the account back to good standing.",
        "success": "Payment received — your account has been reinstated.",
        "title": "Outstanding balance",
        "viewInvoice": "View unpaid invoice"
      },
      "states": {
        "pastDue": {
          "description": "A payment for this subscription was declined and is being retried automatically. Settle the outstanding balance below to avoid the account being suspended.",
          "title": "Payment failed — action needed"
        },
        "pending": {
          "description": "The first payment for this subscription is being processed. This page will reflect the result once the charge resolves.",
          "title": "Subscription pending"
        },
        "suspended": {
          "description": "Sending is disabled because the outstanding balance was not settled. Settle it below to reinstate the account and re-enable sending.",
          "title": "Account suspended for non-payment"
        }
      },
      "title": "Billing"
    },
    "plans": {
      "alreadySubscribed": {
        "descriptionPrefix": "A workspace may hold only one subscription at a time. Manage the current subscription from the ",
        "descriptionSuffix": ".",
        "link": "billing overview",
        "title": "This workspace already has a subscription"
      },
      "card": {
        "includedSends": "{{sends}} sends included",
        "overageBilled": "Overage billed at {{price}} per send",
        "overageBlocked": "Sends over the allowance are blocked",
        "perPeriod": "/ {{period}}",
        "subscribe": "Subscribe"
      },
      "declined": {
        "description": "The first charge for that plan was declined, so the subscription was not activated. You can try subscribing again.",
        "title": "Payment declined"
      },
      "description": "Choose a plan to subscribe this workspace.",
      "dialog": {
        "confirm": "Confirm & pay",
        "description": "You will be charged {{price}} now for the first {{period}} period. The subscription becomes active once the charge succeeds.",
        "processing": "Processing payment…",
        "title": "Subscribe to {{plan}}"
      },
      "empty": {
        "description": "There are no plans to subscribe to right now. Please check back later.",
        "title": "No plans available"
      },
      "loadError": {
        "title": "Could not load plans"
      },
      "title": "Plans",
      "toast": {
        "subscribed": "Subscription active — your plan is now in effect.",
        "subscriptionExists": "This workspace already has a subscription."
      }
    },
    "usage": {
      "blocked": {
        "description": "This plan blocks sends beyond the included allowance. Further campaign starts and transactional sends will be rejected until the next billing period begins.",
        "title": "Allowance reached"
      },
      "closedPeriodsLink": "invoice",
      "closedPeriodsPrefix": "Usage for closed periods is reflected in each period’s ",
      "closedPeriodsSuffix": ".",
      "description": "Metered sends consumed in the current billing period.",
      "loadError": {
        "title": "Could not load usage"
      },
      "noSubscription": {
        "browsePlans": "Browse plans",
        "description": "Subscribe to a plan to start metering usage.",
        "title": "No active subscription"
      },
      "overage": {
        "description_few": "Sends beyond the allowance are billed as overage. {{formattedCount}} overage sends recorded so far this period.",
        "description_many": "Sends beyond the allowance are billed as overage. {{formattedCount}} overage sends recorded so far this period.",
        "description_one": "Sends beyond the allowance are billed as overage. {{formattedCount}} overage send recorded so far this period.",
        "description_other": "Sends beyond the allowance are billed as overage. {{formattedCount}} overage sends recorded so far this period.",
        "title": "Overage billing"
      },
      "refreshNote": {
        "description": "Usage is rolled up by a background process, so sends from the last few minutes may not yet be reflected here.",
        "title": "Figures update periodically"
      },
      "thisPeriod": {
        "title": "This period"
      },
      "title": "Usage"
    }
  },
  "branding": {
    "customCss": {
      "description": "Applied to every public page. Markup that could escape or run scripts is removed by the server.",
      "title": "Custom CSS"
    },
    "forbidden": {
      "description": "You need the branding:manage permission to view this page.",
      "title": "You do not have access"
    },
    "index": {
      "description": "Applies to every one of your tenant's public pages — subscription, preference, archive, and the standalone campaign pages.",
      "title": "Branding"
    },
    "logoColor": {
      "description": "A logo and primary color shown at the top of every public page.",
      "logoUrlHint": "Use an image from your Media library or any public URL.",
      "logoUrlLabel": "Logo URL",
      "logoUrlPlaceholder": "https://",
      "pickFromMedia": "Pick from media",
      "primaryColorLabel": "Primary color",
      "primaryColorPlaceholder": "#RRGGBB",
      "title": "Logo and color"
    },
    "save": {
      "submit": "Save branding",
      "submitting": "Saving…",
      "success": "Branding saved."
    }
  },
  "campaigns": {
    "create": {
      "description": "Name the campaign. You can optionally start from a campaign template, then edit its content.",
      "nameLabel": "Name",
      "nameRequired": "Enter a campaign name.",
      "noTemplate": "No template",
      "submit": "Create campaign",
      "submitting": "Creating…",
      "success": "Campaign created.",
      "templateLabel": "Start from a template (optional)",
      "title": "New campaign"
    },
    "detail": {
      "actions": {
        "cancel": "Cancel campaign",
        "pause": "Pause",
        "resume": "Resume",
        "start": "Start campaign"
      },
      "archive": {
        "description": "When enabled, this campaign appears in the tenant's public archive index, on its standalone page, and in the RSS feed.",
        "hidden": "Campaign is hidden from the public archive.",
        "shown": "Campaign is now visible in the public archive.",
        "title": "Public archive",
        "toggle": "Visible in the public archive"
      },
      "autoPaused": {
        "description": "Sending was paused automatically after reaching {{count}} send errors. Review and resume, or cancel the campaign.",
        "title": "Campaign auto-paused"
      },
      "backToCampaigns": "← Campaigns",
      "confirmCancel": {
        "confirm": "Cancel campaign",
        "description": "The campaign will stop sending and cannot be resumed.",
        "title": "Cancel this campaign?"
      },
      "confirmStart": {
        "confirm": "Start sending",
        "description": "Sending begins immediately and cannot be undone. You can pause or cancel it once running.",
        "title": "Start this campaign?"
      },
      "content": {
        "bodyLabel": "Body",
        "description": "Edit the campaign’s subject and content. HTML is sent as-is.",
        "htmlBodyLabel": "HTML body",
        "insertFromMedia": "Insert from media library",
        "nameLabel": "Name",
        "nameRequired": "Enter a campaign name.",
        "subjectLabel": "Subject",
        "subjectRequired": "Enter a subject.",
        "textBodyLabel": "Plain-text body",
        "title": "Content"
      },
      "domainRequired": {
        "description": "Select a verified sending domain below before this campaign can be started.",
        "title": "A verified sending domain is required"
      },
      "quotaBlocked": {
        "descriptionAfter": " to continue sending.",
        "descriptionBefore": "This campaign was not started because the workspace has used its plan's send allowance for the current period. Review your ",
        "link": "usage and plan",
        "title": "Send allowance reached"
      },
      "recipients": {
        "description": "Select one or more lists to send to.",
        "emptyMessage": "Create a list of subscribers to target.",
        "emptyTitle": "No lists",
        "title": "Recipients"
      },
      "save": "Save changes",
      "saveSuccess": "Campaign saved.",
      "saveWarnings_few": "Campaign saved with {{count}} content warnings.",
      "saveWarnings_many": "Campaign saved with {{count}} content warnings.",
      "saveWarnings_one": "Campaign saved with {{count}} content warning.",
      "saveWarnings_other": "Campaign saved with {{count}} content warnings.",
      "saving": "Saving…",
      "sender": {
        "description": "Choose a verified sending domain and the from address.",
        "domainLabel": "Sending domain",
        "domainPlaceholder": "Select a verified domain",
        "fromLocalPartLabel": "From address (local part)",
        "fromLocalPartPlaceholder": "news",
        "fromNameLabel": "From name",
        "noDomain": "No domain selected",
        "noVerifiedDomains": "No verified domains yet. Verify a domain under Sending Domains first.",
        "title": "Sender"
      },
      "startSuccess": "Campaign started.",
      "summary": {
        "fromLabel": "From: ",
        "subjectLabel": "Subject: "
      },
      "suspendedBlocked": {
        "descriptionAfter": " to re-enable sending.",
        "descriptionBefore": "This campaign was not started because the workspace is suspended for non-payment. Settle the outstanding balance in ",
        "link": "billing",
        "title": "Account suspended"
      },
      "viewAnalytics": "View analytics →"
    },
    "list": {
      "columns": {
        "created": "Created",
        "name": "Name",
        "progress": "Progress",
        "status": "Status"
      },
      "description": "Author and send campaigns to your lists.",
      "emptyMessage": "Create your first campaign to start sending.",
      "emptyTitle": "No campaigns yet",
      "newCampaign": "New campaign",
      "progress": {
        "draft": "—",
        "summary": "{{sent}} sent · {{failed}} failed · {{remaining}} left"
      },
      "title": "Campaigns"
    },
    "sendProgress": {
      "failed": "Failed",
      "remaining": "Remaining",
      "sent": "Sent",
      "title": "Send progress"
    },
    "status": {
      "cancelled": "Cancelled",
      "draft": "Draft",
      "finished": "Finished",
      "paused": "Paused",
      "running": "Running"
    },
    "visual": {
      "convert": "Convert to visual editor",
      "convertedSuccess": "Converted to visual editor. Review and save to keep it.",
      "convertedWarnings_few": "Converted to visual editor with {{count}} blocks preserved as raw HTML. Review and save to keep the visual document.",
      "convertedWarnings_many": "Converted to visual editor with {{count}} blocks preserved as raw HTML. Review and save to keep the visual document.",
      "convertedWarnings_one": "Converted to visual editor with {{count}} block preserved as raw HTML. Review and save to keep the visual document.",
      "convertedWarnings_other": "Converted to visual editor with {{count}} blocks preserved as raw HTML. Review and save to keep the visual document.",
      "converting": "Converting…",
      "forceOverwrite": "Force overwrite",
      "optOut": {
        "confirm": "Switch to HTML only",
        "description": "Your structured visual document will be discarded. The last saved HTML body stays intact so the campaign remains sendable, but blocks, columns, and merge-tag chips will no longer be available unless you convert back later.",
        "switching": "Switching…",
        "title": "Switch to HTML-only editing?"
      },
      "optOutSuccess": "Switched to HTML-only mode. The structured document was cleared.",
      "reload": "Reload",
      "staleTitle": "Changed in another tab/session"
    }
  },
  "common": {
    "account": {
      "menu": "Account menu",
      "settings": "Account settings",
      "signOut": "Sign out",
      "switchWorkspace": "Switch workspace"
    },
    "actions": {
      "cancel": "Cancel",
      "copy": "Copy",
      "logIn": "Log in",
      "next": "Next",
      "preview": "Preview",
      "previous": "Previous",
      "save": "Save",
      "saving": "Saving…",
      "signUp": "Sign up",
      "tryAgain": "Try again"
    },
    "appName": "nvelope",
    "asyncState": {
      "emptyMessage": "There is nothing to show.",
      "emptyTitle": "Nothing here yet",
      "errorTitle": "Could not load this view"
    },
    "clipboard": {
      "copied": "Copied",
      "copyFailed": "Could not copy — copy the URL manually.",
      "copyToClipboardFailed": "Could not copy to the clipboard."
    },
    "cssEditor": {
      "counter": "{{used}} / {{limit}} bytes",
      "hint": "CSS is sanitized server-side before it is applied to your public pages. Limit: {{limit}} bytes.",
      "label": "Custom CSS",
      "overLimit": "Reduce the CSS below the limit before saving.",
      "sanitizedHeading": "Sanitized CSS applied to your public pages"
    },
    "dnsRecordRow": {
      "copied": "{{label}} copied.",
      "copyLabel": "Copy {{label}}",
      "host": "Host",
      "hostLabel": "{{recordType}} host",
      "value": "Value",
      "valueLabel": "{{recordType}} value"
    },
    "jsonAttributeEditor": {
      "hint": "A JSON object of custom fields stored with this subscriber.",
      "invalidJson": "Not valid JSON.",
      "label": "Custom attributes",
      "mustBeObject": "Attributes must be a JSON object, e.g. { \"plan\": \"pro\" }."
    },
    "landing": {
      "createWorkspace": "Create a workspace",
      "noWorkspacesDescription": "Create your first workspace to get started.",
      "noWorkspacesTitle": "No workspaces yet",
      "signInPrompt": "Sign in to manage your workspaces.",
      "signedInAs": "Signed in as {{name}}.",
      "workspacesTitle": "Your workspaces"
    },
    "mediaPicker": {
      "description": "Pick an asset to insert into the message. Only your tenant's media is shown.",
      "emptyMessage": "Upload files in the Media library before inserting them here.",
      "emptyTitle": "No media yet",
      "openLibrary": "Open Media library",
      "title": "Insert from media library"
    },
    "nav": {
      "access": "People & Access",
      "audit": "Audit",
      "billing": "Billing",
      "branding": "Branding",
      "campaigns": "Campaigns",
      "dashboard": "Dashboard",
      "group": "Workspace",
      "importExport": "Import / Export",
      "lists": "Lists",
      "media": "Media",
      "publicPages": "Public pages",
      "sendingDomains": "Sending Domains",
      "settings": "Settings",
      "subscribers": "Subscribers",
      "suppressions": "Suppression list",
      "templates": "Templates",
      "transactional": "Transactional Sending"
    },
    "notFound": {
      "backHome": "Back home",
      "description": "The page you were looking for does not exist.",
      "title": "Page not found"
    },
    "overview": {
      "subtitle": "Everything for this workspace, in one place.",
      "tiles": {
        "access": {
          "description": "Invite teammates and manage roles.",
          "label": "People & Access"
        },
        "audit": {
          "description": "Review recent workspace activity.",
          "label": "Audit"
        },
        "importExport": {
          "description": "Bring subscribers in and out via CSV.",
          "label": "Import / Export"
        },
        "lists": {
          "description": "Organise subscribers into lists.",
          "label": "Lists"
        },
        "settings": {
          "description": "Configure this workspace.",
          "label": "Settings"
        },
        "subscribers": {
          "description": "Browse, search, and manage subscribers.",
          "label": "Subscribers"
        }
      }
    },
    "publicUrlList": {
      "copyLabel": "Copy {{label}}",
      "empty": "No public URLs to share yet.",
      "previewLabel": "Preview {{label}}",
      "tokenHint": "The {token} placeholder is filled in automatically when this link is sent to a subscriber."
    },
    "segmentBuilder": {
      "addCondition": "Condition",
      "addGroup": "Group",
      "attrKeyPlaceholder": "Attribute key",
      "leafKind": {
        "attr": "Attribute",
        "field": "Field",
        "member": "List membership"
      },
      "listIdPlaceholder": "List id",
      "matchAll": "all",
      "matchAny": "any",
      "matchPrefix": "Match",
      "matchSuffix": "of the following",
      "op": {
        "contains": "contains",
        "eq": "equals",
        "exists": "exists",
        "gt": "greater than",
        "gte": "greater or equal",
        "lt": "less than",
        "lte": "less or equal",
        "neq": "not equals"
      },
      "removeCondition": "Remove condition",
      "statusPlaceholder": "Status",
      "valuePlaceholder": "Value"
    },
    "state": {
      "error": "Something went wrong.",
      "loading": "Loading…"
    },
    "suspension": {
      "message": "This workspace is suspended for non-payment. Sending is disabled until the outstanding balance is settled.",
      "settleBalance": "Settle balance"
    },
    "table": {
      "range": "{{from}}–{{to}} of {{total}}"
    },
    "ui": {
      "close": "Close",
      "sidebar": "Sidebar",
      "sidebarDescription": "Displays the mobile sidebar.",
      "toggleSidebar": "Toggle Sidebar"
    },
    "usageMeter": {
      "exhausted": "Plan allowance reached for this period.",
      "nearLimit": "Approaching the plan allowance for this period.",
      "remaining_few": "{{formattedCount}} sends remaining this period.",
      "remaining_many": "{{formattedCount}} sends remaining this period.",
      "remaining_one": "{{formattedCount}} send remaining this period.",
      "remaining_other": "{{formattedCount}} sends remaining this period.",
      "sendsUnit": "sends"
    },
    "workspace": {
      "backToWorkspaces": "Back to your workspaces",
      "fallbackName": "Workspace",
      "loadErrorDescription": "Something went wrong. Please try again.",
      "loadErrorTitle": "Could not load the workspace",
      "notAvailableDescription": "This workspace does not exist, or you are not a member of it.",
      "notAvailableTitle": "Workspace not available",
      "openErrorDescription": "Something went wrong opening this workspace. Please try again.",
      "openErrorTitle": "Could not open the workspace"
    }
  },
  "dashboard": {
    "index": {
      "description": "Deliverability health across this workspace.",
      "emptyMessage": "Once you send a campaign, its delivery health will appear here.",
      "emptyTitle": "No sending activity yet",
      "title": "Dashboard"
    },
    "metrics": {
      "bounced": "Bounced",
      "clicked": "Clicked",
      "complained": "Complained",
      "delivered": "Delivered",
      "opened": "Opened",
      "sent": "Sent"
    },
    "recentCampaigns": {
      "bounceRate": "Bounce",
      "complaintRate": "Complaint",
      "empty": "No campaigns have been sent yet.",
      "openRate": "Open",
      "sentCount_few": "{{count}} sent",
      "sentCount_many": "{{count}} sent",
      "sentCount_one": "{{count}} sent",
      "sentCount_other": "{{count}} sent",
      "title": "Recent campaigns"
    }
  },
  "emails": {
    "verify": {
      "about": "nvelope is a managed platform for building, sending, and tracking newsletters and email campaigns.",
      "button": "Verify email address",
      "greeting": "Hi {{name}}, thanks for creating your nvelope account.",
      "heading": "Confirm your email",
      "ignore": "If you didn't create an nvelope account, you can safely ignore this email — no account will be activated without confirmation.",
      "instruction": "To start building and sending newsletters, please confirm this email address.",
      "linkHint": "If the button doesn't work, copy and paste this link into your browser:",
      "preview": "Confirm your email address to start using nvelope",
      "subject": "Confirm your email address to start using nvelope"
    }
  },
  "errors": {
    "status": {
      "conflict": "That conflicts with something that already exists.",
      "forbidden": "You do not have permission to do that.",
      "generic": "The request could not be completed.",
      "notFound": "The requested resource was not found.",
      "server": "Something went wrong on our end. Please try again.",
      "unauthorized": "You need to sign in to continue.",
      "unprocessable": "Some of the information provided is not valid."
    },
    "unexpected": "An unexpected error occurred."
  },
  "importExport": {
    "export": {
      "cardDescription": "Choose what to export. The result downloads as a CSV.",
      "cardTitle": "Export subscribers",
      "downloadCsv": "Download CSV",
      "listLabel": "List",
      "listPlaceholder": "Choose a list…",
      "selectionAll": "All subscribers",
      "selectionLabel": "Selection",
      "selectionList": "A list",
      "selectionSegment": "A segment",
      "start": "Start export",
      "started": "Export started."
    },
    "import": {
      "cardDescription": "Upload a CSV or ZIP file and choose which lists to add subscribers to.",
      "cardTitle": "Import subscribers",
      "fileLabel": "CSV or ZIP file",
      "noLists": "No lists available.",
      "start": "Start import",
      "started": "Import started.",
      "targetLists": "Target lists"
    },
    "index": {
      "description": "Bring subscribers in from a CSV, or export them out.",
      "title": "Import / Export"
    },
    "job": {
      "createdCount_few": "{{count}} created",
      "createdCount_many": "{{count}} created",
      "createdCount_one": "{{count}} created",
      "createdCount_other": "{{count}} created",
      "failedCount_few": "{{count}} failed",
      "failedCount_many": "{{count}} failed",
      "failedCount_one": "{{count}} failed",
      "failedCount_other": "{{count}} failed",
      "rowCount_few": "{{count}} rows",
      "rowCount_many": "{{count}} rows",
      "rowCount_one": "{{count}} row",
      "rowCount_other": "{{count}} rows",
      "rowFailure": "Row {{row}}: {{reason}}",
      "rowFailures": "Row failures",
      "status": "Status",
      "updatedCount_few": "{{count}} updated",
      "updatedCount_many": "{{count}} updated",
      "updatedCount_one": "{{count}} updated",
      "updatedCount_other": "{{count}} updated"
    },
    "permissionNotice": {
      "description": "You need the “{{permission}}” permission to {{action}}. Ask a workspace admin to grant it.",
      "exportAction": "export subscribers",
      "importAction": "import subscribers",
      "title": "Not available"
    },
    "tabs": {
      "export": "Export",
      "import": "Import"
    }
  },
  "lists": {
    "columns": {
      "created": "Created",
      "description": "Description",
      "name": "Name",
      "visibility": "Visibility"
    },
    "create": {
      "description": "Give the list a name. You can add subscribers afterwards.",
      "submit": "Create list",
      "submitting": "Creating…",
      "success": "List created.",
      "title": "New list"
    },
    "detail": {
      "back": "← Lists",
      "cardTitle": "List details",
      "confirmDeleteDescription": "The list will be removed. Subscribers are not deleted.",
      "confirmDeleteTitle": "Delete this list?",
      "deleteList": "Delete list",
      "deleteSuccess": "List deleted.",
      "saveChanges": "Save changes",
      "subscribersEmptyMessage": "No subscribers are subscribed to this list.",
      "subscribersEmptyTitle": "No subscribers yet",
      "subscribersTitle": "Subscribers in this list",
      "updateSuccess": "List updated."
    },
    "form": {
      "description": "Description",
      "name": "Name",
      "nameRequired": "Enter a list name."
    },
    "index": {
      "description": "Organise subscribers into lists.",
      "emptyMessage": "Create your first list to start grouping subscribers.",
      "emptyTitle": "No lists yet",
      "newList": "New list",
      "title": "Lists"
    },
    "subscriberColumns": {
      "email": "Email",
      "name": "Name",
      "subscription": "Subscription"
    }
  },
  "media": {
    "card": {
      "copyUrl": "Copy URL",
      "deleteAria": "Delete {{filename}}",
      "open": "Open"
    },
    "deleteDialog": {
      "confirm": "Delete",
      "description": "It will be removed from the library. Campaigns that reference its URL will lose the asset.",
      "title": "Delete this asset?"
    },
    "detail": {
      "notFoundDescription": "This asset may have been deleted, or the URL may be wrong.",
      "notFoundTitle": "Asset not found",
      "previewTitle": "Preview",
      "stableUrlTitle": "Stable URL",
      "uploadedMeta": "{{type}} · {{size}} · uploaded {{date}}"
    },
    "forbidden": {
      "assetDescription": "You need the media:get or media:manage permission to view this asset.",
      "libraryDescription": "You need the media:get or media:manage permission to view the library.",
      "title": "You do not have access"
    },
    "library": {
      "backLink": "← Media library",
      "description": "Upload images and documents to reference from your campaigns. Limit per file: {{limit}}.",
      "emptyMessageManage": "Upload your first asset above.",
      "emptyMessageView": "Nothing in the library yet.",
      "emptyTitle": "No media yet",
      "title": "Media library"
    },
    "toast": {
      "copied": "Copied",
      "copyFailed": "Could not copy",
      "deleted": "Deleted.",
      "uploadForbidden": "You do not have permission to upload media.",
      "uploaded": "Uploaded."
    },
    "upload": {
      "allowedTypes": "Allowed types: {{types}}.",
      "button": "Upload file",
      "buttonBusy": "Uploading…",
      "title": "Upload"
    },
    "validation": {
      "tooLarge": "File is too large. The limit is {{limit}}.",
      "typeNotAllowed": "Files of type \"{{type}}\" are not allowed. Allowed: {{allowed}}.",
      "unknownType": "unknown"
    }
  },
  "publicPages": {
    "basics": {
      "active": "Active — visible to visitors at the public URL",
      "description": "The page's identity on the public URL and what visitors see.",
      "pageTitle": "Title",
      "slug": "Slug",
      "slugHint": "Lowercase letters, numbers, and hyphens. Appears in the public URL.",
      "title": "Basics"
    },
    "boundLists": {
      "description": "A confirmed subscriber will be added to every list selected here.",
      "empty": "No lists yet. Create a list first.",
      "loading": "Loading lists…",
      "title": "Bound lists"
    },
    "confirmationEmail": {
      "description": "The double-opt-in confirmation email is sent from this verified sending domain.",
      "fromLocalPart": "From address (local part)",
      "fromLocalPartHint": "The portion before the @ in the From address.",
      "fromName": "From name",
      "selectDomain": "Select a sending domain…",
      "sendingDomain": "Sending domain",
      "title": "Confirmation email"
    },
    "edit": {
      "back": "← Public pages",
      "copied": "Copied",
      "copyFailed": "Could not copy",
      "copyUrl": "Copy URL",
      "create": "Create page",
      "createSuccess": "Subscription page created.",
      "preview": "Preview",
      "save": "Save changes",
      "saving": "Saving…",
      "selectListError": "Select at least one list to subscribe visitors to.",
      "titleEdit": "Edit subscription page",
      "titleNew": "New subscription page",
      "updateSuccess": "Subscription page updated."
    },
    "fields": {
      "addField": "Add field",
      "builtInSuffix": " (built-in)",
      "chooseOption": "Choose a field…",
      "deletedSuffix": "{{key}} (no longer in registry)",
      "description": "Email is always shown and always required. Pick from your subscriber-fields registry to add more — the same list the visual editor's merge-tag picker uses. Manage the registry under Settings → Subscriber fields.",
      "fieldLabel": "Field",
      "labelLabel": "Label",
      "loadingOption": "Loading fields…",
      "noCustomFields": "No custom subscriber fields yet — add one under Settings → Subscriber fields to surface it here.",
      "removeField": "Remove field {{name}}",
      "required": "Required",
      "title": "Fields"
    },
    "forbidden": {
      "description": "You need the subscription_pages:manage permission to view this page.",
      "title": "You do not have access"
    },
    "index": {
      "createFirstPage": "Create your first subscription page",
      "description": "Configure subscription pages, preview public URLs, and share the archive and RSS feed.",
      "emptyMessage": "Create your first subscription page to let visitors join one of your lists.",
      "emptyTitle": "No subscription pages yet",
      "newPage": "New subscription page",
      "shareUrlsDescription": "Copy these to share with subscribers, embed in your site, or point a feed reader at.",
      "shareUrlsTitle": "Share your public URLs",
      "subscriptionPagesDescription": "Active pages are reachable at the public URL below; inactive pages show a \"not available\" message to visitors.",
      "subscriptionPagesTitle": "Subscription pages",
      "title": "Public pages"
    },
    "notFound": {
      "description": "This page may have been deleted, or you may have followed an old link.",
      "title": "Subscription page not found"
    },
    "publicUrls": {
      "archiveIndex": "Archive index",
      "preferenceTemplate": "Preference link template",
      "rssFeed": "RSS feed",
      "subscriptionPage": "Subscription page — {{title}}"
    },
    "row": {
      "active": "Active",
      "edit": "Edit",
      "inactive": "Inactive"
    }
  },
  "security": {
    "apiKeys": {
      "confirmRevokeDescription": "Any integration using this key will immediately stop working.",
      "confirmRevokeLabel": "Revoke key",
      "confirmRevokeTitle": "Revoke this API key?",
      "emptyMessage": "Issue an API key to access the workspace programmatically.",
      "emptyTitle": "No API keys",
      "issue": "Issue API key",
      "issuedDate": "Issued {{date}}",
      "issuedNote": "This secret is shown only once and cannot be retrieved later.",
      "issuedTitle": "Copy your API key now",
      "permissionCount_few": "{{count}} permissions",
      "permissionCount_many": "{{count}} permissions",
      "permissionCount_one": "{{count}} permission",
      "permissionCount_other": "{{count}} permissions",
      "revokeKeyAria": "Revoke key",
      "revokedSuffix": " · revoked",
      "revokedToast": "API key revoked."
    },
    "index": {
      "description": "Two-factor authentication and API keys.",
      "tabs": {
        "apiKeys": "API keys",
        "totp": "Two-factor"
      },
      "title": "Security"
    },
    "issueDialog": {
      "description": "The key’s secret is shown once after it is created.",
      "issuedToast": "API key issued.",
      "nameLabel": "Key name",
      "nameRequired": "Name the key.",
      "permissionsLabel": "Permissions",
      "submit": "Issue key",
      "submitting": "Issuing…",
      "title": "Issue an API key"
    },
    "totp": {
      "cardDescription": "Add a time-based one-time code to workspace sign-in.",
      "cardTitle": "Two-factor authentication",
      "codeLabel": "Authentication code",
      "codeRequired": "Enter the code.",
      "confirm": "Confirm",
      "confirmDisableDescription": "Workspace sign-in will no longer require a one-time code.",
      "confirmDisableLabel": "Disable",
      "confirmDisableTitle": "Disable two-factor authentication?",
      "disable": "Disable two-factor",
      "disabledToast": "Two-factor authentication disabled.",
      "enable": "Enable two-factor",
      "enabledToast": "Two-factor authentication enabled.",
      "openInApp": "Open in authenticator app",
      "recoveryCodesTitle": "Save your recovery codes",
      "secretLabel": "Add this secret to your authenticator app"
    }
  },
  "sendingDomains": {
    "create": {
      "description": "Enter the domain you want to send mail from. You will be shown the DNS records to publish.",
      "domainLabel": "Domain",
      "domainPlaceholder": "mail.example.com",
      "domainRequired": "Enter a domain name.",
      "submit": "Add domain",
      "submitting": "Adding…",
      "success": "Domain added. Publish its DNS records to verify it.",
      "title": "Add a sending domain"
    },
    "detail": {
      "back": "← Sending domains",
      "dkimRecordType": "DKIM ({{type}})",
      "dmarcRecordType": "DMARC (TXT)",
      "dnsDescription": "Publish these records at your DNS provider. Verification runs automatically once they are visible.",
      "dnsTitle": "DNS records",
      "failedTitle": "Verification failed",
      "lastChecked": " Last checked {{date}}.",
      "recheckNow": "Re-check now",
      "recheckRequested": "Re-check requested.",
      "spfRecordType": "SPF (TXT)",
      "verifiedMessage": "Verified {{date}}. You can send campaigns and transactional mail from this domain.",
      "verifiedTitle": "Domain verified"
    },
    "index": {
      "addDomain": "Add domain",
      "added": "Added {{date}}",
      "description": "Verify the domains you send mail from.",
      "emptyMessage": "Add a domain to publish its DNS records and start sending.",
      "emptyTitle": "No sending domains yet",
      "recheckAria": "Re-check domain",
      "recheckRequested": "Re-check requested.",
      "title": "Sending domains"
    },
    "status": {
      "failed": "failed",
      "pending": "pending",
      "verified": "verified"
    }
  },
  "settings": {
    "fields": {
      "addField": "Add field",
      "card": {
        "description": "Built-in fields cannot be renamed or removed.",
        "title": "Fields"
      },
      "delete": {
        "confirmLabel": "Delete field",
        "description": "Existing subscribers keep their attribute data; the registry definition is removed.",
        "title": "Delete \"{{name}}\"?"
      },
      "dialog": {
        "createTitle": "New subscriber field",
        "defaultValue": {
          "label": "Default value"
        },
        "displayName": {
          "label": "Display name",
          "required": "Enter a display name."
        },
        "editTitle": "Edit subscriber field",
        "slug": {
          "label": "Slug",
          "required": "Enter a slug."
        },
        "type": {
          "label": "Type"
        }
      },
      "forbidden": "You do not have permission to manage subscriber fields.",
      "page": {
        "description": "Define the custom subscriber attributes that appear in the merge-tag picker, on subscription pages, and in segment filters.",
        "title": "Subscriber fields"
      },
      "row": {
        "builtIn": "built-in",
        "delete": "Delete",
        "edit": "Edit",
        "moveDown": "Move {{name}} down",
        "moveUp": "Move {{name}} up"
      },
      "table": {
        "default": "Default",
        "displayName": "Display name",
        "emptyDefault": "—",
        "slug": "Slug",
        "type": "Type"
      },
      "toast": {
        "created": "Field created.",
        "deleted": "Field deleted.",
        "saved": "Field saved."
      }
    },
    "form": {
      "description": "These values apply across the whole workspace.",
      "displayName": {
        "label": "Display name",
        "required": "Enter a display name."
      },
      "savedToast": "Settings saved.",
      "submit": "Save settings",
      "timezone": {
        "hint": "An IANA timezone, e.g. Europe/Berlin.",
        "label": "Timezone"
      },
      "title": "Workspace settings"
    },
    "page": {
      "description": "Configure this workspace.",
      "title": "Settings"
    }
  },
  "subscribers": {
    "create": {
      "addToLists": "Add to lists",
      "description": "Add a subscriber with optional attributes and list memberships.",
      "email": "Email",
      "emailTaken": "A subscriber with this email already exists.",
      "name": "Name",
      "noLists": "No lists yet — you can add memberships later.",
      "submit": "Create subscriber",
      "submitting": "Creating…",
      "success": "Subscriber created.",
      "title": "New subscriber"
    },
    "detail": {
      "back": "← Subscribers",
      "deleteConfirm": "Delete subscriber",
      "deleteDescription": "The subscriber and all their list memberships will be removed.",
      "deleteSuccess": "Subscriber deleted.",
      "deleteTitle": "Delete this subscriber?"
    },
    "edit": {
      "delete": "Delete",
      "name": "Name",
      "nameRequired": "Enter a name.",
      "save": "Save changes",
      "saving": "Saving…",
      "state": "State",
      "success": "Subscriber updated."
    },
    "list": {
      "columns": {
        "email": "Email",
        "lists": "Lists",
        "name": "Name",
        "state": "State"
      },
      "description": "Search, segment, and manage subscribers.",
      "newSubscriber": "New subscriber",
      "search": {
        "emptyMessage": "No subscribers match this search.",
        "emptyTitle": "No subscribers found",
        "placeholder": "Search by email or name",
        "submit": "Search"
      },
      "segment": {
        "emptyMessage": "No subscribers match this segment.",
        "emptyTitle": "No matches",
        "matchCount_few": "{{count}} subscribers match this segment.",
        "matchCount_many": "{{count}} subscribers match this segment.",
        "matchCount_one": "{{count}} subscriber matches this segment.",
        "matchCount_other": "{{count}} subscribers match this segment.",
        "run": "Run query"
      },
      "tabs": {
        "search": "Search",
        "segment": "Segment query"
      },
      "title": "Subscribers"
    },
    "memberships": {
      "add": "Add",
      "addPlaceholder": "Add to a list…",
      "addSuccess": "Added to list.",
      "count_few": "{{count}} list memberships",
      "count_many": "{{count}} list memberships",
      "count_one": "{{count}} list membership",
      "count_other": "{{count}} list memberships",
      "empty": "Not a member of any list yet.",
      "removeFromList": "Remove from list",
      "removeSuccess": "Removed from list.",
      "statusSuccess": "Subscription updated.",
      "title": "List memberships"
    }
  },
  "suppressions": {
    "addDialog": {
      "description": "The address will be skipped on all future sends until you remove it.",
      "emailLabel": "Email address",
      "emailPlaceholder": "person@example.com",
      "emailRequired": "Enter an email address.",
      "submit": "Add address",
      "submitting": "Adding…",
      "successToast": "Address added to the suppression list.",
      "title": "Add an address"
    },
    "index": {
      "addAddress": "Add address",
      "allReasons": "All reasons",
      "bounceSettings": "Bounce settings",
      "description": "Addresses that will not be mailed for this workspace.",
      "emptyFilteredMessage": "No suppressed addresses match the current filter.",
      "emptyFilteredTitle": "No matching addresses",
      "emptyMessage": "Bounces and complaints are added here automatically. You can also add an address manually.",
      "emptyTitle": "No suppressed addresses",
      "filterReasonAria": "Filter by reason",
      "loadMore": "Load more",
      "loadingMore": "Loading…",
      "searchAria": "Search by address",
      "searchPlaceholder": "Search by address",
      "title": "Suppression list"
    },
    "reasons": {
      "complaint": "Complaint",
      "hardBounce": "Hard bounce",
      "manual": "Manual"
    },
    "remove": {
      "confirmDescription": "will become mailable again and may receive future campaigns.",
      "confirmLabel": "Remove",
      "confirmTitle": "Remove from suppression list?",
      "successToast": "Address removed from the suppression list."
    },
    "row": {
      "removeAria": "Remove {{email}}",
      "suppressedAt": "Suppressed {{date}}"
    },
    "settings": {
      "back": "Back to suppression list",
      "complaintDescription": "When on, an address that reports a message as spam is added to the suppression list automatically. Turning this off lets the workspace keep mailing recipients who have complained, which damages sender reputation and deliverability.",
      "complaintTitle": "Complaint suppression",
      "complaintToggle": "Suppress addresses that complain",
      "description": "Control how this workspace reacts to delivery feedback.",
      "hardBounceDescription": "When on, an address that hard-bounces is added to the suppression list automatically. Turning this off lets the workspace keep mailing addresses that permanently reject mail, which damages sender reputation.",
      "hardBounceTitle": "Hard-bounce suppression",
      "hardBounceToggle": "Suppress addresses that hard-bounce",
      "save": "Save settings",
      "savedToast": "Bounce-action settings saved.",
      "saving": "Saving…",
      "title": "Bounce-action settings"
    }
  },
  "templates": {
    "create": {
      "description": "Templates can be used for campaigns or transactional sending.",
      "htmlBodyLabel": "HTML body",
      "nameLabel": "Name",
      "nameRequired": "Enter a template name.",
      "subjectLabel": "Subject",
      "subjectRequired": "Enter a subject.",
      "submit": "Create template",
      "submitting": "Creating…",
      "success": "Template created.",
      "textBodyLabel": "Plain-text body",
      "title": "New template",
      "typeLabel": "Type"
    },
    "detail": {
      "backToTemplates": "← Templates",
      "bodyLabel": "Body",
      "htmlBodyLabel": "HTML body",
      "nameLabel": "Name",
      "nameRequired": "Enter a template name.",
      "save": "Save changes",
      "saveSuccess": "Template saved.",
      "saveWarnings_few": "Template saved with {{count}} content warnings.",
      "saveWarnings_many": "Template saved with {{count}} content warnings.",
      "saveWarnings_one": "Template saved with {{count}} content warning.",
      "saveWarnings_other": "Template saved with {{count}} content warnings.",
      "saving": "Saving…",
      "subjectLabel": "Subject",
      "subjectRequired": "Enter a subject.",
      "textBodyLabel": "Plain-text body"
    },
    "kind": {
      "campaign": "Campaign",
      "transactional": "Transactional"
    },
    "list": {
      "columns": {
        "kind": "Kind",
        "name": "Name",
        "subject": "Subject",
        "updated": "Updated"
      },
      "confirmDelete": {
        "confirm": "Delete template",
        "description": "The template will be removed. Campaigns already built from it keep their content.",
        "title": "Delete this template?"
      },
      "deleteAction": "Delete template",
      "deleteSuccess": "Template deleted.",
      "description": "Reusable content for campaigns and transactional mail.",
      "emptyMessage": "Create a template to reuse content across campaigns.",
      "emptyTitle": "No templates yet",
      "newTemplate": "New template",
      "title": "Templates"
    },
    "visual": {
      "convert": "Convert to visual editor",
      "convertedSuccess": "Converted to visual editor. Review and save to keep it.",
      "convertedWarnings_few": "Converted to visual editor with {{count}} blocks preserved as raw HTML. Review and save to keep the visual document.",
      "convertedWarnings_many": "Converted to visual editor with {{count}} blocks preserved as raw HTML. Review and save to keep the visual document.",
      "convertedWarnings_one": "Converted to visual editor with {{count}} block preserved as raw HTML. Review and save to keep the visual document.",
      "convertedWarnings_other": "Converted to visual editor with {{count}} blocks preserved as raw HTML. Review and save to keep the visual document.",
      "converting": "Converting…",
      "forceOverwrite": "Force overwrite",
      "optOut": {
        "confirm": "Switch to HTML only",
        "description": "Your structured visual document will be discarded. The last saved HTML body stays intact so the template remains usable, but blocks, columns, and merge-tag chips will no longer be available unless you convert back later.",
        "switching": "Switching…",
        "title": "Switch to HTML-only editing?"
      },
      "optOutSuccess": "Switched to HTML-only mode. The structured document was cleared.",
      "reload": "Reload",
      "staleTitle": "Changed in another tab/session"
    }
  },
  "transactional": {
    "apiKeys": {
      "confirmRevokeDescription": "Any integration using this key will immediately stop working.",
      "confirmRevokeLabel": "Revoke key",
      "confirmRevokeTitle": "Revoke this API key?",
      "copyNowDescription": "This secret is shown only once and cannot be retrieved later. If you lose it, revoke the key and issue a new one.",
      "copyNowTitle": "Copy your API key now",
      "description": "Keys scoped for transactional sending.",
      "emptyMessage": "Issue an API key to integrate transactional sending.",
      "emptyTitle": "No API keys",
      "issueKey": "Issue API key",
      "issued": "Issued {{date}}",
      "restrictedDescription": "You do not have permission to issue or revoke API keys in this workspace.",
      "restrictedTitle": "Key management is restricted",
      "revokeKey": "Revoke key",
      "revokeSuccess": "API key revoked.",
      "revokedSuffix": " · revoked",
      "title": "API keys"
    },
    "domainAlert": {
      "description": "Transactional sends will fail until at least one sending domain is verified. Verify a domain under Sending Domains first.",
      "title": "A verified sending domain is required"
    },
    "endpoint": {
      "description": "Send transactional mail by calling this endpoint with the API key above as a Bearer token.",
      "endpointLabel": "Endpoint",
      "errorNoteEnd": " if transactional sends start failing.",
      "errorNoteLink": "billing",
      "errorNotePrefix": "The endpoint responds ",
      "errorNoteQuota": " when the workspace has used its plan's send allowance, or ",
      "errorNoteSuspended": " when the account is suspended for non-payment. Check ",
      "errorNoteWith": " with ",
      "requestBodyLabel": "Request body",
      "templateNoteEmphasis": "transactional",
      "templateNotePrefix": "Each request must reference an existing ",
      "templateNoteSuffix": " template by id and a verified sending domain id.",
      "title": "Endpoint reference"
    },
    "index": {
      "description": "Issue a scoped API key and integrate the transactional endpoint.",
      "title": "Transactional sending"
    },
    "issueDialog": {
      "descriptionPrefix": "The key is scoped to ",
      "descriptionSuffix": ". Its secret is shown once after it is created.",
      "issue": "Issue key",
      "issueSuccess": "API key issued.",
      "issuing": "Issuing…",
      "keyName": "Key name",
      "nameRequired": "Name the key.",
      "title": "Issue a transactional API key"
    }
  },
  "visualEditor": {
    "bubbleMenu": {
      "apply": "Apply",
      "colorPrompt": "Color (CSS hex / rgb / name):",
      "linkPlaceholder": "https://…"
    },
    "mergeTag": {
      "closeAriaLabel": "Close",
      "dialogAriaLabel": "Insert merge tag",
      "filterPlaceholder": "Type to filter…",
      "groupCampaign": "Campaign",
      "groupSubscriber": "Subscriber",
      "loadError": "Failed to load merge tags.",
      "loading": "Loading…",
      "noMatches": "No matches.",
      "title": "Insert merge tag"
    },
    "preview": {
      "desktop": "Desktop ({{width}}px)",
      "error": "Preview failed: {{message}}",
      "iframeTitle": "Email preview",
      "mobile": "Mobile ({{width}}px)",
      "viewportAriaLabel": "Preview viewport"
    },
    "rawHtmlModal": {
      "description": "These bytes are passed through verbatim. They run through the sanitizer at save time — disallowed constructs (script, event handlers, dangerous URL schemes) are stripped.",
      "editorAriaLabel": "Raw HTML editor",
      "save": "Save HTML",
      "title": "Edit raw HTML block"
    },
    "theme": {
      "buttonColor": "Button color",
      "buttonTextColor": "Button text color",
      "colorSwatchAriaLabel": "{{label}} swatch",
      "containerWidth": "Container width (px)",
      "fontFamily": "Font family",
      "inheritBadge": "Using tenant defaults",
      "inheritHint": "This row uses the tenant's branding. Pin an override to customize colors, font, and container width just for this row.",
      "linkColor": "Link color",
      "panelAriaLabel": "Theme controls",
      "pinOverride": "Pin a theme override",
      "pinnedBadge": "Pinned override",
      "resetDefaults": "Reset to tenant defaults",
      "textColor": "Text color",
      "title": "Theme"
    },
    "toolbar": {
      "editHtmlOnly": "Edit as HTML only",
      "viewHtml": "View HTML"
    }
  }
}
